name: Deploy to Netlify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Copy Files to Deploy Directory
        run: |
          rsync -a --delete main/ deploy/
        working-directory: ${{ github.workspace }}

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Deploy to Netlify
        run: |
          echo "Starting Netlify deployment..."
          netlify login -i $NETLIFY_AUTH_TOKEN
          cd deploy
          netlify deploy --prod --site ${{ secrets.NETLIFY_SITE_NAME }}
        working-directory: ${{ github.workspace }}/deploy
